name: hafiz_tafkeed
description: تطبيق حافز التركيز
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  intl: ^0.18.1
  # google_fonts: ^6.3.3  # ❌ مشكلة على الويب بدون dev mode
  # shared_preferences: ^2.5.5  # ❌ مشكلة على الويب بدون dev mode
  # path_provider: ^2.1.6  # ❌ مشكلة على الويب بدون dev mode

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true